require:
  - rubocop-rails
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'vendor/bundle/**/*'

Style/Documentation:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/**/*'

Metrics/BlockLength:
  Exclude:
    - 'db/migrate/**/*'
    - 'config/**/*.rb'
