version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: reedr
      POSTGRES_PASSWORD: dev
      POSTGRES_MULTIPLE_DATABASES: reedr_development,reedr_test
    volumes:
      - ./db/initdb:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
